FROM node:alpine
WORKDIR /app/frontend
RUN chown $(id -u node):$(id -g node) $(pwd)
USER node
COPY --chown=node:node ./package.json .
RUN npm install
COPY --chown=node:node . .
EXPOSE 3000
CMD ["npm", "start"]
