import axios from 'axios';
import { useEffect, useState } from 'react';
import NewTask from './components/NewTask';
import TaskList from './components/TaskList';

const client = axios.create({
  baseURL: '/api',
});

const App = () => {
  const [tasks, setTasks] = useState([]);
  const [error, setError] = useState(null);

  // For the first page hit, fetch every task from backend DB.
  useEffect(() => {
    client
      .get('/tasks')
      .then((response) => {
        setTasks(response.data);
        console.log(response.data);
      })
      .catch((err) => {
        setError(err);
      });
  }, []);

  // Handler for Add Task button.
  const addTaskHandler = (task) => {
    // send POST request and append the response data to array `tasks`.
    // The response comes with an ID generated by the backend DB.
    client .post('/tasks', task) .then((response) => {
        setTasks((prevTasks) => [...prevTasks, response.data]);
      })
      .catch((err) => {
        setError(err);
      });
  };

  // Handler for Delete button.
  const deleteTaskHandler = (task) => {
    // send DELETE request and delete the task up on reception from backend DB
    console.log('trying to delete: ');
    console.log(task);
    client
      .delete(`/tasks/${task._id}`)
      .then(() => {
        setTasks((prevTasks) =>
          prevTasks.filter((elem) => elem._id !== task._id)
        );
      })
      .catch((err) => {
        setError(err);
      });
  };

  if (error) {
    return <h2>{`Error: ${error.message}`}</h2>;
  }

  return (
    <div>
      <NewTask onAddTask={addTaskHandler} />
      <TaskList tasks={tasks} onDeleteTask={deleteTaskHandler} />
    </div>
  );
};

export default App;
