FROM node:20-alpine
WORKDIR /app/api
RUN chown $(id -u node):$(id -g node) $(pwd)
USER node
RUN chown $(id -u):$(id -g) $(pwd)
COPY --chown=node:node ./package*.json ./
RUN npm ci
COPY --chown=node:node . .
EXPOSE 4000
CMD ["npm", "run", "dev"]
