name: Destroy Preview for Closed Pull Request
env:
  NAMESPACE: preview-todo-keikekke
  PIPELINE_RESULT_NAME: pr-${{ github.event.number }}
on:
  pull_request:
    types:
      - closed
jobs:
  Destroy-Preview-Okteto:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Login
        uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: "Activate Namespace"
        uses: okteto/namespace@latest
        with:
          namespace: ${{ env.NAMESPACE }}

      - name: "Destroy the pipeline"
        uses: okteto/destroy-pipeline@latest
        with:
          name: ${{ env.PIPELINE_RESULT_NAME }}
